include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    always_declare_return_types: true
